services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: k7-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate --url http://k7-api:8000
    depends_on:
      k7-api:
        condition: service_healthy
    networks:
      - k7-network

  k7-api:
    image: ${K7_API_IMAGE:-ghcr.io/katakate/k7-api}:${K7_API_TAG:-latest}
    pull_policy: if_not_present
    container_name: k7-api
    restart: unless-stopped
    user: "0:0"
    volumes:
      - /etc/rancher/k3s/k3s.yaml:/etc/rancher/k3s/k3s.yaml:ro
      - /etc/k7:/etc/k7
    environment:
      - KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      - K7_API_KEYS_FILE=/etc/k7/api_keys.json
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import sys,urllib.request; sys.exit(0) if urllib.request.urlopen(\"http://127.0.0.1:8000/health\", timeout=2).status==200 else sys.exit(1)' "]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - k7-network

networks:
  k7-network:
    driver: bridge 